### ISSUE TITLE
Support the `.python-version` file

### ISSUE THREAD

**Issue by edmorley** [heroku/buildpacks-python#6]
We should support the `.python-version` file as a means for specifying what Python version an app is using.

This file format (used by pyenv and others) now also supports specifying Python versions in the X.Y format (and not just X.Y.Z), making it a strong contender over the Heroku-specific `runtime.txt` file.

Officially supported syntax:
- `3.12.6`
- `3.12`
- comments (lines starting with `#`)
- blank lines
- pyenv supports specifying multiple versions, however, this buildpack can't, so we'll either want to only use the first version, or error if there are multiple versions specified

Unofficially supported syntax:
- `python-3.12.6`
- `python-3.12` (though this currently has a bug: https://github.com/pyenv/pyenv/issues/3054)

...though the `python-` forms are undocumented and likely going to be deprecated soon (https://github.com/pyenv/pyenv/issues/3054#issuecomment-2341316638), so I'm leaning towards not supporting them.

For more background, see:
- https://github.com/heroku/heroku-buildpack-python/issues/932
- https://github.com/heroku/heroku-buildpack-python/issues/913#issuecomment-1031468659
- [Internal tracking epic](https://gus.lightning.force.com/lightning/r/ADM_Epic__c/a3QEE000000V4wz2AC/view)

**Comment by edmorley** [comment]
I found a bug in pyenv's handling of some of the more obscure syntax variants, which I filed as:
https://github.com/pyenv/pyenv/issues/3054

And have opened https://github.com/pyenv/pyenv/pull/3056 to fix.

**Comment by edmorley** [comment]
@megahall Hi! This repository is for the Heroku Python Cloud Native Buildpack (the next generation of buildpacks, currently in preview), rather than the existing (classic) Heroku Python buildpack, which is at:
https://github.com/heroku/heroku-buildpack-python

Support for Poetry and `.python-version` will be backported to the classic buildpack soon, but if you wanted to try out the Python CNB in the meantime, there is more information here:
https://github.com/heroku/buildpacks

**Comment by edmorley** [comment]
> Support for Poetry and `.python-version` will be backported to the classic buildpack soon

To track that, subscribe to:
- https://github.com/heroku/heroku-buildpack-python/issues/932
- https://github.com/heroku/heroku-buildpack-python/issues/796

**Comment by merwok** [comment]
> if you wanted to try out the Python CNB in the meantime, there is more information here

I was curious about this, as I’ve been following recent activity, but all the docs I found talk about running tools locally, not using the CNB on heroku.

**Comment by edmorley** [comment]
> all the docs I found talk about running tools locally, not using the CNB on heroku.

Yeah it's currently not possible to use CNBs on Heroku (only locally using the Pack CLI), however, that's coming soon:
https://github.com/heroku/roadmap/issues/20

**Comment by edmorley** [comment]
If there is a way to make this clearer in the docs, feedback welcome :-)

(This repo's README has a banner [here](https://github.com/heroku/buildpacks-python/blob/288f8221f77a9d60b53b3a863843510b38968915/README.md?plain=1#L12-L13) which links to a CNB overview repo that links to the roadmap item [here](https://github.com/heroku/buildpacks/blob/39f73c9348a2dfe1814dc9b7ea84185765fdaa4b/README.md?plain=1#L12) - but perhaps the latter needs a specific banner call-out?)
